# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
